lib/condorest/web/router.ex
defmodule Condorest.Web.Router do
  use Condorest.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Condorest.Auth, repo: Condorest.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Condorest.Web do
    pipe_through :browser # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/", PageController, :index
  end

  scope "/", Condorest.Web do
    pipe_through [:browser, :authenticate_user]

    resources "/users", UserController
    resources "/lots", LotController
    resources "/lot_types", LotTypeController, only: [:new, :create, :index, :delete, :edit, :update]
    resources "/contacts", ContactController
    resources "/accounts", AccountController
    resources "/entries", EntryController
    resources "/receipts", ReceiptController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Condorest.Web do
  #   pipe_through :api
  # end
end

lib/condorest/web/views/layout_view.ex
defmodule Condorest.Web.LayoutView do
  use Condorest.Web, :view
end

lib/condorest/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Condorest!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="row-offcanvas row-offcanvas-left">
    <div id="sidebar" class="sidebar-offcanvas">
    <div class="col-md-12">
      <h2>CondoREST</h2>
      <ul>
        <%= if @current_user do %>
        <li><label class="nav-header">Entities</label></li>
        <ul class="">
          <li><%= link "Lots", to: lot_path(@conn, :index) %></li>
          <li><%= link "Contacts", to: contact_path(@conn, :index) %></li>
          <li><%= link "Lot types", to: lot_type_path(@conn, :index) %></li>
        </ul>
        <li><label class="nav-header">Ledger</label></li>
        <ul class="">
          <li><%= link "Accounts", to: account_path(@conn, :index) %></li>
          <li><%= link "Entries", to: entry_path(@conn, :index) %></li>
        </ul>
        <li><label class="nav-header">Revenue</label></li>
        <ul class="">
          <li><%= link "Receipts", to: receipt_path(@conn, :index) %></li>
        </ul>
        <li><label class="nav-header">Session</label></li>
        <ul class="">
            <li><%= @current_user.username %></li>
            <li><%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
        <% else %>
            <li><%= link "Log in", to: session_path(@conn, :new) %></li>
        <% end %>
        </ul>
      </ul>
    </div> <!-- /col -->
    </div> <!-- /sidebar -->

    <div id="main">
    <div class="col-md-12">
      <button class="sidebar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <svg height="20px" id="Layer_1" style="enable-background:new 0 0 32 32;" version="1.1" viewBox="0 0 32 32" width="20px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M4,10h24c1.104,0,2-0.896,2-2s-0.896-2-2-2H4C2.896,6,2,6.896,2,8S2.896,10,4,10z M28,14H4c-1.104,0-2,0.896-2,2  s0.896,2,2,2h24c1.104,0,2-0.896,2-2S29.104,14,28,14z M28,22H4c-1.104,0-2,0.896-2,2s0.896,2,2,2h24c1.104,0,2-0.896,2-2  S29.104,22,28,22z"/></svg>
      </button>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /col -->
    </div> <!-- /main -->
    </div> <!-- /row -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>